version: '3.8'

services:
  modbus-bridge:
    build: .
    container_name: modbus-bridge
    restart: unless-stopped
    env_file:
      - config.env
    ports:
      - "5020:5020"
    networks:
      - modbus-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  modbus-network:
    driver: bridge
